project:
  output-dir: docs
  type: website
  render:
    - index.qmd
    - acesso/index.qmd
    - expedicoes/index.qmd
    - team/index.qmd
    - en/index.qmd
    - en/data-access/index.qmd
    - en/expeditions/index.qmd
    - en/team/index.qmd
  resources:
    - figures/**
    - js/**
    - css/**

website:
  title: "Tsiino Hiwiida"
  page-navigation: true
  reader-mode: false
  search: false
  favicon: "figures/tsiino_hex_sticker.png"
  navbar:
    search: false
    background: light
    collapse-below: lg
    type: light
    logo: "figures/tsiino_hex_sticker.png"
    href: index.qmd
    left:
      - text: "Sobre"
        href: index.qmd
      - text: "Expedições"
        href: expedicoes/index.qmd
      - text: "Acesso aos dados"
        href: acesso/index.qmd
      - text: "Equipe"
        href: team/index.qmd
      - text: "EN"
        href: en/

format:
  html:
    toc: true
    embed-resources: false
    self-contained: false
    code-copy: true
    code-overflow: wrap
    code-tools: false
    css:
      - styles.css
      - css/language-toggle.css
    eval: true
    theme: [spacelab, theme.scss]
    include-in-header: gtm-head.html
    include-before-body: gtm-body.html
    include-after-body:
      - tsiino-footer.html
      - _includes/language-router.html
