
# -*- coding: utf-8 -*-
from __future__ import annotations
INPA_FIELDS = [
 {"name":"accession","label":"Registro INPA","required":False,"help":"Número de registro no herbário INPA. Em planilhas de coleta, normalmente pode ficar em branco."},
 {"name":"collector","label":"Coletor principal","required":True,"help":"Nome do coletor principal. Exemplo: Silva, L.L."},
 {"name":"prefix","label":"Prefixo","required":False,"help":"Use apenas quando houver prefixo real."},
 {"name":"number","label":"Número de coleta","required":True,"help":"Número de coleta."},
 {"name":"suffix","label":"Sufixo","required":False,"help":"Use somente se o número de coleta exigir sufixo."},
 {"name":"addcoll","label":"Coletores adicionais","required":False,"help":"Demais pessoas presentes na coleta."},
 {"name":"colldd","label":"Dia da coleta","required":True,"help":"Dia da coleta, em número."},
 {"name":"collmm","label":"Mês da coleta","required":True,"help":"Mês da coleta, em número."},
 {"name":"collyy","label":"Ano da coleta","required":True,"help":"Ano da coleta com quatro dígitos."},
 {"name":"initial","label":"Nº de amostras","required":False,"help":"Número de amostras/indivíduos, quando aplicável."},
 {"name":"family","label":"Família","required":True,"help":"Família botânica."},
 {"name":"genus","label":"Gênero","required":True,"help":"Gênero botânico."},
 {"name":"detstatus","label":"cf./aff.","required":False,"help":"Status de determinação, como cf. ou aff."},
 {"name":"sp1","label":"Epíteto específico","required":False,"help":"Epíteto específico."},
 {"name":"rank1","label":"Rank infraespecífico","required":False,"help":"Rank infraespecífico."},
 {"name":"sp2","label":"Epíteto infraespecífico","required":False,"help":"Epíteto infraespecífico."},
 {"name":"detby","label":"Determinador","required":False,"help":"Pessoa responsável pela determinação."},
 {"name":"detdd","label":"Dia da determinação","required":False,"help":"Dia da determinação."},
 {"name":"detmm","label":"Mês da determinação","required":False,"help":"Mês da determinação."},
 {"name":"detyy","label":"Ano da determinação","required":False,"help":"Ano da determinação."},
 {"name":"country","label":"País","required":True,"help":"País da coleta."},
 {"name":"majorarea","label":"Estado","required":True,"help":"UF/estado."},
 {"name":"minorarea","label":"Município","required":True,"help":"Município da coleta."},
 {"name":"gazetteer","label":"Localidade","required":False,"help":"Localidade detalhada."},
 {"name":"locnotes","label":"Notas da localidade","required":False,"help":"Notas complementares da localidade."},
 {"name":"habitattxt","label":"Habitat","required":False,"help":"Descrição do habitat."},
 {"name":"lat","label":"Latitude","required":True,"help":"Latitude em graus decimais."},
 {"name":"NS","label":"N/S","required":False,"help":"Hemisfério da latitude."},
 {"name":"long","label":"Longitude","required":True,"help":"Longitude em graus decimais."},
 {"name":"EW","label":"E/W","required":False,"help":"Hemisfério da longitude."},
 {"name":"llunit","label":"Unidade lat/long","required":False,"help":"Unidade das coordenadas."},
 {"name":"alt","label":"Altitude","required":False,"help":"Altitude em metros."},
 {"name":"alt1","label":"Altitude 2","required":False,"help":"Altitude complementar."},
 {"name":"plantdesc","label":"Descrição da planta","required":True,"help":"Descrição da planta em campo."},
 {"name":"vernacular","label":"Nome popular","required":False,"help":"Nome vernacular."},
 {"name":"dups","label":"Duplicatas","required":False,"help":"Herbários de duplicatas."},
 {"name":"project","label":"Projeto","required":False,"help":"Projeto associado."},
 {"name":"genbank","label":"GenBank","required":False,"help":"Identificador GenBank."},
]
INPA_FIELD_NAMES=[f["name"] for f in INPA_FIELDS]
REQUIRED_FIELDS=[f["name"] for f in INPA_FIELDS if f["required"]]
